### ISSUE TITLE
Additional API for populating our front end

### ISSUE THREAD

**Issue by fstamenkovic** [kennylee9672/ECS193A#15]
We will need to populate our tables at the front page. To give you an idea of what a table looks like, here's an image of a table filled with hard coded values:

![image](https://user-images.githubusercontent.com/34168715/80665472-32618700-8a5f-11ea-915f-8d41bed398fd.png)

In order to fill this table, we need an API that will returns a JSON with all retailers in our database, and their associated grades and a logo for them. Having logos would be nice but I guess we can get away without them for now. The most important part now is the retailers and grades. A sample JSON response:

![image](https://user-images.githubusercontent.com/34168715/80665871-435ec800-8a60-11ea-828e-c153c99ac269.png)

We will deal with sorting the retailers in the front end. Don't worry about worst or best companies.

Thanks!

@rmsepic

**Comment by ShafiTek** [comment]
Done. Check README.
